### ISSUE TITLE
Add user friendly method for adding additional secret patterns

### ISSUE THREAD

**Issue by rileydakota** [sirwart/ripsecrets#5]
Hi! 

Love the tool! The performance gains are awesome! Curious if you had any plans to make adding additional secret patterns to the tool more friendly (Maybe an external TOML file with user specified patterns?). If you could forsee this being part of the tool, would love to pull together a PR if we can agree on an implementation.

Otherwise - would be happy to PR some additional secret patterns!

**Comment by sfc-gh-brsmith** [comment]
Thanks! I think user configurable patterns are on the list of things that I want to support but have been waiting for a motivating use case for. Do you have an example you want to support?

**Comment by colindean** [comment]
I'd like to catch:

* Old-style GitHub tokens, which are still used in still-supported GitHub Enterprise installations (although this _could_ be added to the prepackaged list, but probably shouldn't because the old-style ones didn't really have set format)
* My company's internal OAuth API key format

**Comment by sirwart** [comment]
My initial thought is to have something like a `.secretpatterns` file that is similar to the `.gitignore` file where each line is a new pattern. `ripsecrets` would look in the git root as well as the users home directory for this file when searching. What do folks think?

**Comment by colindean** [comment]
I'd prefer to have _one_ file for all ripsecrets config, if possible. Config file format could remain simple: I know it's easy to reach for serde but there might be something more lightweight that keeps the code and binary small.

**Comment by colindean** [comment]
Are regex patterns enough? I think so but there's some allure in embedding a scripting language like Lua or [Passerine](https://docs.rs/passerine/latest/passerine/).

**Comment by sirwart** [comment]
All the patterns are defined by regex currently, and that's what makes it so fast, so I would definitely want to start with custom regex patterns.

**Comment by kengodwin** [comment]
I'd like to +1 this feature as well.

**Comment by sirwart** [comment]
@pkgh-mp secrets in URLs should probably be supported by default. I can take a crack at adding that soon.

@kengodwin I can also look at adding custom regex patterns to search for. It's pretty trivial to support, just need to decide on how to specify it.

**Comment by kengodwin** [comment]
Appreciate it when you have the time, thanks for looking into it.

**Comment by sirwart** [comment]
I just published a new release that allows you to specify additional secret regexes using the `--additional-pattern` CLI argument. I chose against having a config file for now since if you're using it as a precommit hook you can specify the CLI arguments as part of the hook, which avoids the complexity of adding yet another config file to your repo.

@pkgh-mp in addition to the above, passwords in URLs are now detected by default (not just MySQL connection strings). It will check for the randomness of the secret to avoid reporting things like example connection strings.

I'm going to close this issue for now but if anyone feels like they need the ability to define the secrets via config file please open a new issue.
